Fix compiler errors with GCC 7.
error: 'std::ostream& zxing::operator<<(std::ostream&, zxing::Result&)' has not been declared within zxing

Unused variable warnings.